### ISSUE TITLE
设置的默认高度不生效

### ISSUE THREAD

**Issue by 1615958039** [941477276/Tablet#1]
发现源码中有个地方写错了。感谢作者开源，支持一下
![2MSS2_0Z_TAN1BTVF753e9.png](http://www.s3tu.com/images/2020/10/30/2MSS2_0Z_TAN1BTVF753e9.png)

**Comment by 941477276** [comment]
谢谢指正，我更新了一下代码，新版本已经解决了你发现的问题，并且还添加了`设置背景颜色`、`设置背景图片`两个新功能
